name: Build and Deploy receipt Docker Image

on:
  push:
    branches:
      - main
      - yolo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.YOLO_DOCKER_USERNAME }}
        password: ${{ secrets.YOLO_DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker buildx build --no-cache --push -t ${{ secrets.YOLO_DOCKER_USERNAME }}/receipt-image:latest ./receipt
